channels:
  - conda-forge

# conda-managed dependencies
dependencies:
  - python=3.8.12
  - ujson=4.2.0
  - tensorflow=2.6.0
  - pip=21.3.1

  # pip-managed dependencies
  - pip:
      - rasa==2.8.13
      - wheel==0.37.0
      - spacy==3.2.0
