channels:
  - conda-forge

# conda-managed dependencies
dependencies:
  - python=3.8.12
  - regex=2021.7.6

  - pandas=1.3.3
  - numpy=1.18.5
  - scikit-learn=0.24.2

  - networkx=2.5.1
  - graphviz=2.49.0
  - python-graphviz=0.17

  - pip=21.2.4

  # pip-managed dependencies
  - pip:
      - rasa==2.8.7
      - spacy==3.1.3
      - mysql-connector-python==8.0.26
      - sanic-jwt==1.6.0
