# This is a basic workflow to help you get started with Actions

name: Rasa X CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ rasax ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  train_model:
    name: Train Rasa Model
    runs-on: ubuntu-latest
    steps:
      # Checks-out GitHub repository
      # more: https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Run rasa train
      - name: Run rasa train
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: '2.8.0'
          rasa_image: 'noopliez/rasa-spacy-de-md:2.8.0'
          rasa_test: false
          github_token: ${{ secrets.RASA_GHA_TOKEN }}
      - name: Set Model Name
        if: github.ref == 'refs/heads/rasax'
        run: |
          model_path=`ls models/*.tar.gz | head -n 1`
          echo "MODEL_PATH=${model_path}" >> $GITHUB_ENV
          curl -k -F "model=@${{ env.MODEL_PATH }}" "http://34.159.228.55/api/projects/rasa-x-332920/models?api_token=${{ secrets.RASA_TOKEN }}"
  
